name: Vérification validité fichiers

on:
  schedule:
    - cron: "0 8 * * *"   # Vérifie tous les jours à 8h UTC
  workflow_dispatch:      # Permet de lancer manuellement aussi

jobs:
  check-validity:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installer dépendances
        run: pip install pandas openpyxl streamlit

      - name: Vérifier la validité des fichiers
        run: python suivi_validite.py
